image:
  tag: 6.13.0-jmx

datadog:
  apiKey: XXX
  confd:
    presto.yaml: |-
      ad_identifiers:
        - prestosql
      init_config:
        is_jmx: true
        collect_default_metrics: true
      instances:
        - host: "%%host%%"
          port: "9999"

kubeStateMetrics:
  enabled: false

daemonset:
  useConfigMap: true
  tolerations:
    - key: "special"
      operator: "Equal"
      value: "presto"
      effect: "NoExecute"