version: 2
jobs:
  build:
    filters:
      tags:
        only: /.*/
    docker:
      - image: alpine
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              curl bash docker      
      - run: ./build.sh 1.0
