version: 2
jobs:
  build:
    filters:
      tags:
        only: /.*/
    docker:
      - image: circleci/openjdk:8u212-jdk-stretch 
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              curl bash docker maven
      - run: ./build.sh 1.0
